### ISSUE TITLE
卡片信息显示页，显示字段作以下优化

### ISSUE THREAD

**Issue by VonChenPlus** [VonChenPlus/PosManagement#38]
![2](https://cloud.githubusercontent.com/assets/3349963/12233298/0f8c2292-b8a1-11e5-84c4-ec7908ff089b.png)
1、卡号显示 前4位，末4位，中间显示 ****。 
2、增加 卡所属银行   “所属银行“，增加 ”信用额度“
3、”卡主联系电话“ 改为”联系电话“
4、”所属业务员“ 改为”业务员“。若为业务员登录，这列就不显示了。
以上优化后的，显示顺序从左至右为“ 序号  卡号  信用额度 账单日 所属银行  持卡人 联系电话 业务员“
5、上头增加 搜索功能，搜索项为：卡号  银行  持卡人  若为管理员，还有业务员搜索项。搜索应该支持模湖

**Comment by zyga501** [comment]
ok
