### ISSUE TITLE
机具维护显示页

### ISSUE THREAD

**Issue by VonChenPlus** [VonChenPlus/PosManagement#40]
1、机具列表 显示 序号 机具名称  行业 费率  封顶情况 （或为封顶机，显示封顶额，若不封顶，则显示”无“） ，服务商，mcc,  启用时间，使用笔数，刷卡总额  当前状态。若为管理员登录还应 有“业务员“

2、顶部增加 搜索功能  搜索项为  机具名称  行业， 费率 服务商  状态 支持模糊

**Comment by zyga501** [comment]
ok
