### ISSUE TITLE
添加账单优化

### ISSUE THREAD

**Issue by VonChenPlus** [VonChenPlus/PosManagement#42]
1、此处我的理解是这样的   若选择了 账单期，直接点添加账单，则生成自己名下已选账单期的账单未生成的所有卡的账单，同理，若只选 银行，则生成，当月该业务员名下此银行未生成的所有账单。持卡人，同理
2、若以上理解正确 ，则卡号，这一项，可以取消。没有存在的必要。另持卡人，增加下拉功能，将本业务员下的所有持卡人的姓名加进去。另外，是否可以考虑管理员登录时，此处有业务员列表，选业务员时，将其名下所有本期账单未生成的卡的所有账单？

**Comment by zyga501** [comment]
done!

**Comment by VonChenPlus** [comment]
please pull request
